# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-18 18:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0002_remove_car_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_date', models.DateTimeField(default=datetime.datetime(2019, 5, 18, 18, 46, 57, 376395, tzinfo=utc), verbose_name='race date')),
                ('drivers', models.ManyToManyField(to='race.Driver')),
            ],
        ),
    ]
