# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-18 18:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0003_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 18, 18, 48, 10, 243720, tzinfo=utc), verbose_name='race date'),
        ),
    ]
