# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-18 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0007_auto_20190518_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='race.Driver'),
        ),
    ]
